import 'package:flutter/material.dart';

import '../../../model/counrties_phone.dart';

class CountryDropdown extends StatefulWidget {
  @override
  _CountryDropdownState createState() => _CountryDropdownState();
}

class _CountryDropdownState extends State<CountryDropdown> {

  List<Country>countries = [
    Country( name: "Afghanistan", code: "AF", phone: 93 ),
   Country( name: "Aland Islands", code: "AX", phone: 358 ),
   Country( name: "Albania", code: "AL", phone: 355 ),
   Country( name: "Algeria", code: "DZ", phone: 213 ),
   Country( name: "American Samoa", code: "AS", phone: 1684 ),
   Country( name: "Andorra", code: "AD", phone: 376 ),
   Country( name: "Angola", code: "AO", phone: 244 ),
   Country( name: "Anguilla", code: "AI", phone: 1264 ),
   Country( name: "Antarctica", code: "AQ", phone: 672 ),
   Country( name: "Antigua and Barbuda", code: "AG", phone: 1268 ),
   Country( name: "Argentina", code: "AR", phone: 54 ),
   Country( name: "Armenia", code: "AM", phone: 374 ),
   Country( name: "Aruba", code: "AW", phone: 297 ),
   Country( name: "Australia", code: "AU", phone: 61 ),
   Country( name: "Austria", code: "AT", phone: 43 ),
   Country( name: "Azerbaijan", code: "AZ", phone: 994 ),
   Country( name: "Bahamas", code: "BS", phone: 1242 ),
   Country( name: "Bahrain", code: "BH", phone: 973 ),
   Country( name: "Bangladesh", code: "BD", phone: 880 ),
   Country( name: "Barbados", code: "BB", phone: 1246 ),
   Country( name: "Belarus", code: "BY", phone: 375 ),
   Country( name: "Belgium", code: "BE", phone: 32 ),
   Country( name: "Belize", code: "BZ", phone: 501 ),
   Country( name: "Benin", code: "BJ", phone: 229 ),
   Country( name: "Bermuda", code: "BM", phone: 1441 ),
   Country( name: "Bhutan", code: "BT", phone: 975 ),
   Country( name: "Bolivia", code: "BO", phone: 591 ),
   Country( name: "Bonaire, Sint Eustatius and Saba", code: "BQ", phone: 599 ),
   Country( name: "Bosnia and Herzegovina", code: "BA", phone: 387 ),
   Country( name: "Botswana", code: "BW", phone: 267 ),
   Country( name: "Bouvet Island", code: "BV", phone: 55 ),
   Country( name: "Brazil", code: "BR", phone: 55 ),
   Country( name: "British Indian Ocean Territory", code: "IO", phone: 246 ),
   Country( name: "Brunei Darussalam", code: "BN", phone: 673 ),
   Country( name: "Bulgaria", code: "BG", phone: 359 ),
   Country( name: "Burkina Faso", code: "BF", phone: 226 ),
   Country( name: "Burundi", code: "BI", phone: 257 ),
   Country( name: "Cambodia", code: "KH", phone: 855 ),
   Country( name: "Cameroon", code: "CM", phone: 237 ),
   Country( name: "Canada", code: "CA", phone: 1 ),
   Country( name: "Cape Verde", code: "CV", phone: 238 ),
   Country( name: "Cayman Islands", code: "KY", phone: 1345 ),
   Country( name: "Central African Republic", code: "CF", phone: 236 ),
   Country( name: "Chad", code: "TD", phone: 235 ),
   Country( name: "Chile", code: "CL", phone: 56 ),
   Country( name: "China", code: "CN", phone: 86 ),
   Country( name: "Christmas Island", code: "CX", phone: 61 ),
   Country( name: "Cocos (Keeling) Islands", code: "CC", phone: 672 ),
   Country( name: "Colombia", code: "CO", phone: 57 ),
   Country( name: "Comoros", code: "KM", phone: 269 ),
   Country( name: "Congo", code: "CG", phone: 242 ),
   Country( name: "Congo, Democratic Republic of the Congo", code: "CD", phone: 242 ),
   Country( name: "Cook Islands", code: "CK", phone: 682 ),
   Country( name: "Costa Rica", code: "CR", phone: 506 ),
   Country( name: "Cote D'Ivoire", code: "CI", phone: 225 ),
   Country( name: "Croatia", code: "HR", phone: 385 ),
   Country( name: "Cuba", code: "CU", phone: 53 ),
   Country( name: "Curacao", code: "CW", phone: 599 ),
   Country( name: "Cyprus", code: "CY", phone: 357 ),
   Country( name: "Czech Republic", code: "CZ", phone: 420 ),
   Country( name: "Denmark", code: "DK", phone: 45 ),
   Country( name: "Djibouti", code: "DJ", phone: 253 ),
   Country( name: "Dominica", code: "DM", phone: 1767 ),
   Country( name: "Dominican Republic", code: "DO", phone: 1809 ),
   Country( name: "Ecuador", code: "EC", phone: 593 ),
   Country( name: "Egypt", code: "EG", phone: 20 ),
   Country( name: "El Salvador", code: "SV", phone: 503 ),
   Country( name: "Equatorial Guinea", code: "GQ", phone: 240 ),
   Country( name: "Eritrea", code: "ER", phone: 291 ),
   Country( name: "Estonia", code: "EE", phone: 372 ),
   Country( name: "Ethiopia", code: "ET", phone: 251 ),
   Country( name: "Falkland Islands (Malvinas)", code: "FK", phone: 500 ),
   Country( name: "Faroe Islands", code: "FO", phone: 298 ),
   Country( name: "Fiji", code: "FJ", phone: 679 ),
   Country( name: "Finland", code: "FI", phone: 358 ),
   Country( name: "France", code: "FR", phone: 33 ),
   Country( name: "French Guiana", code: "GF", phone: 594 ),
   Country( name: "French Polynesia", code: "PF", phone: 689 ),
   Country( name: "French Southern Territories", code: "TF", phone: 262 ),
   Country( name: "Gabon", code: "GA", phone: 241 ),
   Country( name: "Gambia", code: "GM", phone: 220 ),
   Country( name: "Georgia", code: "GE", phone: 995 ),
   Country( name: "Germany", code: "DE", phone: 49 ),
   Country( name: "Ghana", code: "GH", phone: 233 ),
   Country( name: "Gibraltar", code: "GI", phone: 350 ),
   Country( name: "Greece", code: "GR", phone: 30 ),
   Country( name: "Greenland", code: "GL", phone: 299 ),
   Country( name: "Grenada", code: "GD", phone: 1473 ),
   Country( name: "Guadeloupe", code: "GP", phone: 590 ),
   Country( name: "Guam", code: "GU", phone: 1671 ),
   Country( name: "Guatemala", code: "GT", phone: 502 ),
   Country( name: "Guernsey", code: "GG", phone: 44 ),
   Country( name: "Guinea", code: "GN", phone: 224 ),
   Country( name: "Guinea-Bissau", code: "GW", phone: 245 ),
   Country( name: "Guyana", code: "GY", phone: 592 ),
   Country( name: "Haiti", code: "HT", phone: 509 ),
   Country( name: "Heard Island and McDonald Islands", code: "HM", phone: 0 ),
   Country( name: "Holy See (Vatican City State)", code: "VA", phone: 39 ),
   Country( name: "Honduras", code: "HN", phone: 504 ),
   Country( name: "Hong Kong", code: "HK", phone: 852 ),
   Country( name: "Hungary", code: "HU", phone: 36 ),
   Country( name: "Iceland", code: "IS", phone: 354 ),
   Country( name: "India", code: "IN", phone: 91 ),
   Country( name: "Indonesia", code: "ID", phone: 62 ),
   Country( name: "Iran, Islamic Republic of", code: "IR", phone: 98 ),
   Country( name: "Iraq", code: "IQ", phone: 964 ),
   Country( name: "Ireland", code: "IE", phone: 353 ),
   Country( name: "Isle of Man", code: "IM", phone: 44 ),
   Country( name: "Israel", code: "IL", phone: 972 ),
   Country( name: "Italy", code: "IT", phone: 39 ),
   Country( name: "Jamaica", code: "JM", phone: 1876 ),
   Country( name: "Japan", code: "JP", phone: 81 ),
   Country( name: "Jersey", code: "JE", phone: 44 ),
   Country( name: "Jordan", code: "JO", phone: 962 ),
   Country( name: "Kazakhstan", code: "KZ", phone: 7 ),
   Country( name: "Kenya", code: "KE", phone: 254 ),
   Country( name: "Kiribati", code: "KI", phone: 686 ),
   Country( name: "Korea, Democratic People's Republic of", code: "KP", phone: 850 ),
   Country( name: "Korea, Republic of", code: "KR", phone: 82 ),
   Country( name: "Kosovo", code: "XK", phone: 383 ),
   Country( name: "Kuwait", code: "KW", phone: 965 ),
   Country( name: "Kyrgyzstan", code: "KG", phone: 996 ),
   Country( name: "Lao People's Democratic Republic", code: "LA", phone: 856 ),
   Country( name: "Latvia", code: "LV", phone: 371 ),
   Country( name: "Lebanon", code: "LB", phone: 961 ),
   Country( name: "Lesotho", code: "LS", phone: 266 ),
   Country( name: "Liberia", code: "LR", phone: 231 ),
   Country( name: "Libyan Arab Jamahiriya", code: "LY", phone: 218 ),
   Country( name: "Liechtenstein", code: "LI", phone: 423 ),
   Country( name: "Lithuania", code: "LT", phone: 370 ),
   Country( name: "Luxembourg", code: "LU", phone: 352 ),
   Country( name: "Macao", code: "MO", phone: 853 ),
   Country( name: "Macedonia, the Former Yugoslav Republic of", code: "MK", phone: 389 ),
   Country( name: "Madagascar", code: "MG", phone: 261 ),
   Country( name: "Malawi", code: "MW", phone: 265 ),
   Country( name: "Malaysia", code: "MY", phone: 60 ),
   Country( name: "Maldives", code: "MV", phone: 960 ),
   Country( name: "Mali", code: "ML", phone: 223 ),
   Country( name: "Malta", code: "MT", phone: 356 ),
   Country( name: "Marshall Islands", code: "MH", phone: 692 ),
   Country( name: "Martinique", code: "MQ", phone: 596 ),
   Country( name: "Mauritania", code: "MR", phone: 222 ),
   Country( name: "Mauritius", code: "MU", phone: 230 ),
   Country( name: "Mayotte", code: "YT", phone: 262 ),
   Country( name: "Mexico", code: "MX", phone: 52 ),
   Country( name: "Micronesia, Federated States of", code: "FM", phone: 691 ),
   Country( name: "Moldova, Republic of", code: "MD", phone: 373 ),
   Country( name: "Monaco", code: "MC", phone: 377 ),
   Country( name: "Mongolia", code: "MN", phone: 976 ),
   Country( name: "Montenegro", code: "ME", phone: 382 ),
   Country( name: "Montserrat", code: "MS", phone: 1664 ),
   Country( name: "Morocco", code: "MA", phone: 212 ),
   Country( name: "Mozambique", code: "MZ", phone: 258 ),
   Country( name: "Myanmar", code: "MM", phone: 95 ),
   Country( name: "Namibia", code: "NA", phone: 264 ),
   Country( name: "Nauru", code: "NR", phone: 674 ),
   Country( name: "Nepal", code: "NP", phone: 977 ),
   Country( name: "Netherlands", code: "NL", phone: 31 ),
   Country( name: "Netherlands Antilles", code: "AN", phone: 599 ),
   Country( name: "New Caledonia", code: "NC", phone: 687 ),
   Country( name: "New Zealand", code: "NZ", phone: 64 ),
   Country( name: "Nicaragua", code: "NI", phone: 505 ),
   Country( name: "Niger", code: "NE", phone: 227 ),
   Country( name: "Nigeria", code: "NG", phone: 234 ),
   Country( name: "Niue", code: "NU", phone: 683 ),
   Country( name: "Norfolk Island", code: "NF", phone: 672 ),
   Country( name: "Northern Mariana Islands", code: "MP", phone: 1670 ),
   Country( name: "Norway", code: "NO", phone: 47 ),
   Country( name: "Oman", code: "OM", phone: 968 ),
   Country( name: "Pakistan", code: "PK", phone: 92 ),
   Country( name: "Palau", code: "PW", phone: 680 ),
   Country( name: "Palestinian Territory, Occupied", code: "PS", phone: 970 ),
   Country( name: "Panama", code: "PA", phone: 507 ),
   Country( name: "Papua New Guinea", code: "PG", phone: 675 ),
   Country( name: "Paraguay", code: "PY", phone: 595 ),
   Country( name: "Peru", code: "PE", phone: 51 ),
   Country( name: "Philippines", code: "PH", phone: 63 ),
   Country( name: "Pitcairn", code: "PN", phone: 64 ),
   Country( name: "Poland", code: "PL", phone: 48 ),
   Country( name: "Portugal", code: "PT", phone: 351 ),
   Country( name: "Puerto Rico", code: "PR", phone: 1787 ),
   Country( name: "Qatar", code: "QA", phone: 974 ),
   Country( name: "Reunion", code: "RE", phone: 262 ),
   Country( name: "Romania", code: "RO", phone: 40 ),
   Country( name: "Russian Federation", code: "RU", phone: 7 ),
   Country( name: "Rwanda", code: "RW", phone: 250 ),
   Country( name: "Saint Barthelemy", code: "BL", phone: 590 ),
   Country( name: "Saint Helena", code: "SH", phone: 290 ),
   Country( name: "Saint Kitts and Nevis", code: "KN", phone: 1869 ),
   Country( name: "Saint Lucia", code: "LC", phone: 1758 ),
   Country( name: "Saint Martin", code: "MF", phone: 590 ),
   Country( name: "Saint Pierre and Miquelon", code: "PM", phone: 508 ),
   Country( name: "Saint Vincent and the Grenadines", code: "VC", phone: 1784 ),
   Country( name: "Samoa", code: "WS", phone: 684 ),
   Country( name: "San Marino", code: "SM", phone: 378 ),
   Country( name: "Sao Tome and Principe", code: "ST", phone: 239 ),
   Country( name: "Saudi Arabia", code: "SA", phone: 966 ),
   Country( name: "Senegal", code: "SN", phone: 221 ),
   Country( name: "Serbia", code: "RS", phone: 381 ),
   Country( name: "Serbia and Montenegro", code: "CS", phone: 381 ),
   Country( name: "Seychelles", code: "SC", phone: 248 ),
   Country( name: "Sierra Leone", code: "SL", phone: 232 ),
   Country( name: "Singapore", code: "SG", phone: 65 ),
   Country( name: "St Martin", code: "SX", phone: 721 ),
   Country( name: "Slovakia", code: "SK", phone: 421 ),
   Country( name: "Slovenia", code: "SI", phone: 386 ),
   Country( name: "Solomon Islands", code: "SB", phone: 677 ),
   Country( name: "Somalia", code: "SO", phone: 252 ),
   Country( name: "South Africa", code: "ZA", phone: 27 ),
   Country( name: "South Georgia and the South Sandwich Islands", code: "GS", phone: 500 ),
   Country( name: "South Sudan", code: "SS", phone: 211 ),
   Country( name: "Spain", code: "ES", phone: 34 ),
   Country( name: "Sri Lanka", code: "LK", phone: 94 ),
   Country( name: "Sudan", code: "SD", phone: 249 ),
   Country( name: "Suriname", code: "SR", phone: 597 ),
   Country( name: "Svalbard and Jan Mayen", code: "SJ", phone: 47 ),
   Country( name: "Swaziland", code: "SZ", phone: 268 ),
   Country( name: "Sweden", code: "SE", phone: 46 ),
   Country( name: "Switzerland", code: "CH", phone: 41 ),
   Country( name: "Syrian Arab Republic", code: "SY", phone: 963 ),
   Country( name: "Taiwan, Province of China", code: "TW", phone: 886 ),
   Country( name: "Tajikistan", code: "TJ", phone: 992 ),
   Country( name: "Tanzania, United Republic of", code: "TZ", phone: 255 ),
   Country( name: "Thailand", code: "TH", phone: 66 ),
   Country( name: "Timor-Leste", code: "TL", phone: 670 ),
   Country( name: "Togo", code: "TG", phone: 228 ),
   Country( name: "Tokelau", code: "TK", phone: 690 ),
   Country( name: "Tonga", code: "TO", phone: 676 ),
   Country( name: "Trinidad and Tobago", code: "TT", phone: 1868 ),
   Country( name: "Tunisia", code: "TN", phone: 216 ),
   Country( name: "Turkey", code: "TR", phone: 90 ),
   Country( name: "Turkmenistan", code: "TM", phone: 7370 ),
   Country( name: "Turks and Caicos Islands", code: "TC", phone: 1649 ),
   Country( name: "Tuvalu", code: "TV", phone: 688 ),
   Country( name: "Uganda", code: "UG", phone: 256 ),
   Country( name: "Ukraine", code: "UA", phone: 380 ),
   Country( name: "United Arab Emirates", code: "AE", phone: 971 ),
   Country( name: "United Kingdom", code: "GB", phone: 44 ),
   Country( name: "United States", code: "US", phone: 1 ),
   Country( name: "United States Minor Outlying Islands", code: "UM", phone: 1 ),
   Country( name: "Uruguay", code: "UY", phone: 598 ),
   Country( name: "Uzbekistan", code: "UZ", phone: 998 ),
   Country( name: "Vanuatu", code: "VU", phone: 678 ),
   Country( name: "Venezuela", code: "VE", phone: 58 ),
   Country( name: "Viet Nam", code: "VN", phone: 84 ),
   Country( name: "Virgin Islands, British", code: "VG", phone: 1284 ),
   Country( name: "Virgin Islands, U.s.", code: "VI", phone: 1340 ),
   Country( name: "Wallis and Futuna", code: "WF", phone: 681 ),
   Country( name: "Western Sahara", code: "EH", phone: 212 ),
   Country( name: "Yemen", code: "YE", phone: 967 ),
   Country( name: "Zambia", code: "ZM", phone: 260 ),
   Country( name: "Zimbabwe", code: "ZW", phone: 263 )
  ];
  Country? selectedCountry;

  @override
  Widget build(BuildContext context) {
    return DropdownButton<Country>(
      value: selectedCountry,
      icon: Icon(Icons.arrow_downward),
      iconSize: 15,
      style: TextStyle(color: Colors.deepPurple),
      onChanged: (Country? newValue) {
        setState(() {
          selectedCountry = newValue;
        });
      },
      items: countries.map<DropdownMenuItem<Country>>((Country country) {
        return DropdownMenuItem<Country>(
          value: country,
          child: Container(
            width: 90,
            child: Row(
            children: <Widget>[
                Text(
                  country.code,
                  style: TextStyle(color: Colors.black),
                ),
                SizedBox(width: 10),
                Text(
                  "+${country.phone}",
                  style: TextStyle(color: Colors.black),
                ),
              ],
            ),
          ),
        );
      }).toList(),
    );
  }
}